name: Tests
on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize]

jobs:
  test_lint:
    name: Test Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
      - name: Run Linters
         run: lerna run lint